import localFont from "next/font/local";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AdminDashboardProvider } from "@/context/AdminDashboardContext";
import { BanProvider } from "@/context/BanContext";
import { AuthProvider } from "@/context/AuthContext";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <AuthProvider>
            <AdminDashboardProvider>
              <BanProvider>{children}</BanProvider>
            </AdminDashboardProvider>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}